import { Skill, TrainingProgram, JobPosting, StudentProfile, PlacementOutcome } from './types';

export const INITIAL_SKILLS: Skill[] = [
  {
    id: 'skill-1',
    name: 'Electric Vehicle (EV) Powertrain Diagnostics',
    category: 'Emerging Tech',
    sector: 'Automotive & EV',
    demandScore: 96,
    trend: 'Rapidly Rising',
    avgSalaryINR: '₹7,20,000',
    growthRateYoY: '+48%',
    prerequisites: ['Automotive Electronics', 'High Voltage Safety', 'Battery Management Systems (BMS)'],
  },
  {
    id: 'skill-2',
    name: 'Cloud & Kubernetes Infrastructure Ops',
    category: 'Technical',
    sector: 'Information Technology',
    demandScore: 94,
    trend: 'Rapidly Rising',
    avgSalaryINR: '₹9,50,000',
    growthRateYoY: '+34%',
    prerequisites: ['Linux Administration', 'Docker Containerization', 'CI/CD Pipelines'],
  },
  {
    id: 'skill-3',
    name: 'Generative AI & LLM Application Engineering',
    category: 'Emerging Tech',
    sector: 'Information Technology',
    demandScore: 98,
    trend: 'Rapidly Rising',
    avgSalaryINR: '₹14,00,000',
    growthRateYoY: '+82%',
    prerequisites: ['Python', 'API Integrations', 'Prompt Engineering', 'Vector Embeddings'],
  },
  {
    id: 'skill-4',
    name: 'Industrial IoT & SCADA Automation',
    category: 'Technical',
    sector: 'Advanced Manufacturing',
    demandScore: 89,
    trend: 'Rising',
    avgSalaryINR: '₹6,80,000',
    growthRateYoY: '+26%',
    prerequisites: ['PLC Programming', 'Sensor Networks', 'MQTT / Modbus Protocol'],
  },
  {
    id: 'skill-5',
    name: 'Solar PV Plant Design & Grid Integration',
    category: 'Domain',
    sector: 'Renewable Energy',
    demandScore: 88,
    trend: 'Rising',
    avgSalaryINR: '₹6,20,000',
    growthRateYoY: '+31%',
    prerequisites: ['Electrical Engineering', 'HelioScope / PVSyst', 'Safety Standards IEC'],
  },
  {
    id: 'skill-6',
    name: 'Regulatory BFSI Compliance & Fraud Analytics',
    category: 'Domain',
    sector: 'BFSI & FinTech',
    demandScore: 86,
    trend: 'Stable',
    avgSalaryINR: '₹8,10,000',
    growthRateYoY: '+19%',
    prerequisites: ['Financial Modeling', 'SQL', 'RBI Regulatory Guidelines'],
  },
  {
    id: 'skill-7',
    name: 'CNC Precision Machining & 5-Axis Milling',
    category: 'Technical',
    sector: 'Advanced Manufacturing',
    demandScore: 83,
    trend: 'Stable',
    avgSalaryINR: '₹5,40,000',
    growthRateYoY: '+15%',
    prerequisites: ['G-Code Programming', 'CAD/CAM SolidWorks', 'Metrology'],
  },
  {
    id: 'skill-8',
    name: 'Healthcare Clinical Data Annotation & HIPAA',
    category: 'Domain',
    sector: 'Healthcare',
    demandScore: 81,
    trend: 'Rising',
    avgSalaryINR: '₹5,80,000',
    growthRateYoY: '+22%',
    prerequisites: ['Medical Terminology', 'EHR Systems', 'Data Privacy Standards'],
  },
];

export const INITIAL_PROGRAMS: TrainingProgram[] = [
  {
    id: 'prog-1',
    name: 'Advanced EV Technician & Battery Systems Diploma',
    instituteName: 'Government Polytechnic Pune (Aundh)',
    district: 'Pune',
    sector: 'Automotive & EV',
    durationWeeks: 24,
    enrolledStudents: 120,
    placementRate: 88,
    avgPlacementSalaryINR: '₹6,50,000',
    alignmentScore: 92,
    skills: [
      { skillId: 'skill-1', skillName: 'EV Powertrain Diagnostics', proficiencyLevel: 'Advanced', hours: 80, relevanceScore: 96 },
      { skillId: 'sub-1', skillName: 'Lithium Battery Assembly', proficiencyLevel: 'Intermediate', hours: 50, relevanceScore: 90 },
      { skillId: 'sub-2', skillName: 'CAN Bus Protocols', proficiencyLevel: 'Intermediate', hours: 40, relevanceScore: 85 },
    ],
    lastAnalyzedAt: '2026-09-28',
    syllabusSummary: 'Comprehensive vocational program covering high-voltage battery safety, motor controllers, thermal runaway prevention, and regenerative braking diagnostics.',
    status: 'Active',
  },
  {
    id: 'prog-2',
    name: 'Industrial Robotics & CNC Automation Certificate',
    instituteName: 'Industrial Training Institute (ITI) Nashik',
    district: 'Nashik',
    sector: 'Advanced Manufacturing',
    durationWeeks: 16,
    enrolledStudents: 85,
    placementRate: 74,
    avgPlacementSalaryINR: '₹4,80,000',
    alignmentScore: 68,
    skills: [
      { skillId: 'skill-7', skillName: 'CNC Precision Machining', proficiencyLevel: 'Intermediate', hours: 60, relevanceScore: 83 },
      { skillId: 'legacy-1', skillName: 'Legacy Manual Lathe Operations', proficiencyLevel: 'Advanced', hours: 70, relevanceScore: 35 },
    ],
    lastAnalyzedAt: '2026-09-25',
    syllabusSummary: 'Curriculum contains high ratio of obsolete manual machining (lathe/shaper) with insufficient modern 5-axis CNC & IoT sensor coverage.',
    status: 'Revision Mandated',
  },
  {
    id: 'prog-3',
    name: 'Applied Cloud Computing & DevOps Engineering',
    instituteName: 'VJTI Centre of Excellence, Mumbai',
    district: 'Mumbai',
    sector: 'Information Technology',
    durationWeeks: 20,
    enrolledStudents: 140,
    placementRate: 94,
    avgPlacementSalaryINR: '₹9,80,000',
    alignmentScore: 95,
    skills: [
      { skillId: 'skill-2', skillName: 'Cloud & Kubernetes Ops', proficiencyLevel: 'Advanced', hours: 90, relevanceScore: 94 },
      { skillId: 'skill-3', skillName: 'Generative AI Integrations', proficiencyLevel: 'Intermediate', hours: 45, relevanceScore: 98 },
    ],
    lastAnalyzedAt: '2026-09-29',
    syllabusSummary: 'Modern syllabus aligned directly with AWS/Azure/GCP cloud native architectures, GitOps, and microservice observability.',
    status: 'Active',
  },
  {
    id: 'prog-4',
    name: 'Solar Grid Technicians & Microgrid Operations',
    instituteName: 'Government ITI Aurangabad (Chhatrapati Sambhajinagar)',
    district: 'Aurangabad',
    sector: 'Renewable Energy',
    durationWeeks: 12,
    enrolledStudents: 65,
    placementRate: 79,
    avgPlacementSalaryINR: '₹5,10,000',
    alignmentScore: 84,
    skills: [
      { skillId: 'skill-5', skillName: 'Solar PV Plant Design', proficiencyLevel: 'Intermediate', hours: 60, relevanceScore: 88 },
      { skillId: 'sub-4', skillName: 'Inverter Synchronization', proficiencyLevel: 'Intermediate', hours: 30, relevanceScore: 82 },
    ],
    lastAnalyzedAt: '2026-09-27',
    syllabusSummary: 'Prepares technicians for decentralized agricultural solar feeders (PM-KUSUM) and utility-scale solar parks across Marathwada.',
    status: 'Active',
  },
  {
    id: 'prog-5',
    name: 'Digital Logistics & Supply Chain Telematics',
    instituteName: 'Government Polytechnic Nagpur',
    district: 'Nagpur',
    sector: 'Advanced Manufacturing',
    durationWeeks: 16,
    enrolledStudents: 90,
    placementRate: 72,
    avgPlacementSalaryINR: '₹4,50,000',
    alignmentScore: 64,
    skills: [
      { skillId: 'sub-5', skillName: 'Warehouse ERP Systems', proficiencyLevel: 'Foundational', hours: 40, relevanceScore: 65 },
      { skillId: 'legacy-2', skillName: 'Paper-based Waybill Registry', proficiencyLevel: 'Foundational', hours: 35, relevanceScore: 20 },
    ],
    lastAnalyzedAt: '2026-09-22',
    syllabusSummary: 'MIHAN multi-modal cargo hub in Nagpur urgently requires RFID telematics, automated sortation, and fleet route optimization modules.',
    status: 'Under Review',
  },
];

export const INITIAL_JOBS: JobPosting[] = [
  {
    id: 'job-1',
    title: 'Senior EV Diagnostics & Battery Integration Engineer',
    company: 'Tata Motors Passenger Vehicles Ltd.',
    location: 'Pimpri-Chinchwad, Pune',
    sector: 'Automotive & EV',
    jobType: 'Full-time',
    salaryMinINR: 650000,
    salaryMaxINR: 900000,
    experienceLevel: 'Entry-Level',
    requiredSkills: ['Electric Vehicle (EV) Powertrain Diagnostics', 'High Voltage Safety', 'Battery Management Systems (BMS)'],
    preferredSkills: ['CANoe / Vector CANalyzer', 'Thermal Management'],
    vacancies: 35,
    postedDate: '2026-09-28',
    source: 'Direct Partner',
    description: 'Lead line diagnostics for the Curvv EV and Nexon.ev assembly lines. Diagnose telemetry anomalies, supervise module packaging, and ensure ISO 26262 compliance.',
    matchedCandidatesCount: 28,
  },
  {
    id: 'job-2',
    title: 'Junior Cloud Site Reliability Associate',
    company: 'Infosys Cloud Innovation Center',
    location: 'Hinjawadi Phase II, Pune',
    sector: 'Information Technology',
    jobType: 'Full-time',
    salaryMinINR: 750000,
    salaryMaxINR: 1100000,
    experienceLevel: 'Entry-Level',
    requiredSkills: ['Cloud & Kubernetes Infrastructure Ops', 'Linux Administration', 'Docker Containerization'],
    preferredSkills: ['Terraform', 'Prometheus & Grafana'],
    vacancies: 50,
    postedDate: '2026-09-29',
    source: 'LinkedIn Aggregate',
    description: 'Deploy, monitor, and troubleshoot production microservices running on Kubernetes across hybrid cloud installations for Fortune 500 enterprise clients.',
    matchedCandidatesCount: 42,
  },
  {
    id: 'job-3',
    title: 'CNC Programmer & Toolpath Specialist',
    company: 'Bharat Forge Ltd.',
    location: 'Mundhwa, Pune',
    sector: 'Advanced Manufacturing',
    jobType: 'Full-time',
    salaryMinINR: 480000,
    salaryMaxINR: 680000,
    experienceLevel: 'Entry-Level',
    requiredSkills: ['CNC Precision Machining & 5-Axis Milling', 'CAD/CAM SolidWorks', 'G-Code Programming'],
    preferredSkills: ['Metrology CMM', 'Lean Manufacturing'],
    vacancies: 20,
    postedDate: '2026-09-27',
    source: 'Naukri',
    description: 'Program high-precision 5-axis DMG Mori milling centers for aerospace turbine forgings and defense mobility components.',
    matchedCandidatesCount: 14,
  },
  {
    id: 'job-4',
    title: 'Solar Microgrid & SCADA Field Engineer',
    company: 'Mahagenco Renewables & Tata Power Solar',
    location: 'Chhatrapati Sambhajinagar (Aurangabad)',
    sector: 'Renewable Energy',
    jobType: 'Full-time',
    salaryMinINR: 520000,
    salaryMaxINR: 750000,
    experienceLevel: 'Entry-Level',
    requiredSkills: ['Solar PV Plant Design & Grid Integration', 'Industrial IoT & SCADA Automation', 'High Voltage Safety'],
    preferredSkills: ['PVSyst', 'Transformer Maintenance'],
    vacancies: 25,
    postedDate: '2026-09-26',
    source: 'Government Portal',
    description: 'Oversee commissioning and telemetry instrumentation for 50MW ground-mounted solar plants across Marathwada under PM-KUSUM feeder solarization.',
    matchedCandidatesCount: 19,
  },
  {
    id: 'job-5',
    title: 'Associate FinTech Risk & Anti-Fraud Analyst',
    company: 'HDFC Bank Digital Banking Hub',
    location: 'BKC, Mumbai',
    sector: 'BFSI & FinTech',
    jobType: 'Full-time',
    salaryMinINR: 700000,
    salaryMaxINR: 950000,
    experienceLevel: 'Entry-Level',
    requiredSkills: ['Regulatory BFSI Compliance & Fraud Analytics', 'SQL', 'Financial Modeling'],
    preferredSkills: ['Python', 'UPI Transaction Monitoring'],
    vacancies: 30,
    postedDate: '2026-09-29',
    source: 'Direct Partner',
    description: 'Monitor high-frequency UPI 2.0 transactions, detect synthetic identity rings, and report compliance filings in accordance with RBI cyber-security directives.',
    matchedCandidatesCount: 22,
  },
];

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 'stud-1',
    name: 'Aditya Deshmukh',
    email: 'aditya.deshmukh@students.gov.in',
    district: 'Pune',
    instituteName: 'Government Polytechnic Pune (Aundh)',
    programEnrolled: 'Advanced EV Technician & Battery Systems Diploma',
    skills: [
      { skillName: 'Electric Vehicle (EV) Powertrain Diagnostics', level: 'Advanced', verified: true, evidenceType: 'Assessment' },
      { skillName: 'High Voltage Safety', level: 'Advanced', verified: true, evidenceType: 'Industry Certification' },
      { skillName: 'Battery Management Systems (BMS)', level: 'Intermediate', verified: true, evidenceType: 'Coursework' },
      { skillName: 'CAN Bus Protocols', level: 'Intermediate', verified: true, evidenceType: 'GitHub Project' },
    ],
    completionStatus: 'In Progress',
    targetRole: 'Senior EV Diagnostics & Battery Integration Engineer',
    expectedSalaryINR: '₹7,00,000',
    portfolioUrl: 'https://github.com/aditya-ev-telemetry',
    resumeSummary: 'Rank 1 EV Diploma cohort. Built IoT battery pack telemetry dashboard monitoring 72V cell degradation with thermal alerts.',
    matchScoreForTarget: 95,
  },
  {
    id: 'stud-2',
    name: 'Priyanka Patil',
    email: 'priyanka.patil@students.gov.in',
    district: 'Mumbai',
    instituteName: 'VJTI Centre of Excellence, Mumbai',
    programEnrolled: 'Applied Cloud Computing & DevOps Engineering',
    skills: [
      { skillName: 'Cloud & Kubernetes Infrastructure Ops', level: 'Advanced', verified: true, evidenceType: 'Industry Certification' },
      { skillName: 'Linux Administration', level: 'Advanced', verified: true, evidenceType: 'Assessment' },
      { skillName: 'Docker Containerization', level: 'Intermediate', verified: true, evidenceType: 'Coursework' },
      { skillName: 'Generative AI & LLM Application Engineering', level: 'Intermediate', verified: true, evidenceType: 'GitHub Project' },
    ],
    completionStatus: 'Completed',
    targetRole: 'Junior Cloud Site Reliability Associate',
    expectedSalaryINR: '₹8,50,000',
    portfolioUrl: 'https://github.com/priyanka-k8s-mesh',
    resumeSummary: 'Certified Kubernetes Administrator (CKA). Built auto-scaling cluster with GitOps ArgoCD pipeline and Prometheus alerting.',
    matchScoreForTarget: 96,
  },
  {
    id: 'stud-3',
    name: 'Rahul Shinde',
    email: 'rahul.shinde@students.gov.in',
    district: 'Nashik',
    instituteName: 'Industrial Training Institute (ITI) Nashik',
    programEnrolled: 'Industrial Robotics & CNC Automation Certificate',
    skills: [
      { skillName: 'CNC Precision Machining & 5-Axis Milling', level: 'Intermediate', verified: true, evidenceType: 'Coursework' },
      { skillName: 'G-Code Programming', level: 'Intermediate', verified: true, evidenceType: 'Assessment' },
      { skillName: 'CAD/CAM SolidWorks', level: 'Foundational', verified: false, evidenceType: 'Coursework' },
    ],
    completionStatus: 'In Progress',
    targetRole: 'CNC Programmer & Toolpath Specialist',
    expectedSalaryINR: '₹5,00,000',
    portfolioUrl: 'https://grabcad.com/rahul.shinde.cad',
    resumeSummary: '3rd year machinist. Seeking hands-on apprenticeship in defense forging toolpaths with modern CAM training.',
    matchScoreForTarget: 78,
  },
  {
    id: 'stud-4',
    name: 'Sneha Gaikwad',
    email: 'sneha.gaikwad@students.gov.in',
    district: 'Aurangabad',
    instituteName: 'Government ITI Aurangabad (Chhatrapati Sambhajinagar)',
    programEnrolled: 'Solar Grid Technicians & Microgrid Operations',
    skills: [
      { skillName: 'Solar PV Plant Design & Grid Integration', level: 'Advanced', verified: true, evidenceType: 'Assessment' },
      { skillName: 'Industrial IoT & SCADA Automation', level: 'Intermediate', verified: true, evidenceType: 'Coursework' },
      { skillName: 'High Voltage Safety', level: 'Advanced', verified: true, evidenceType: 'Industry Certification' },
    ],
    completionStatus: 'Completed',
    targetRole: 'Solar Microgrid & SCADA Field Engineer',
    expectedSalaryINR: '₹5,80,000',
    portfolioUrl: 'https://linkedin.com/in/sneha-solar-eng',
    resumeSummary: 'Top scorer in Marathwada renewable energy batch. Successfully installed and synchronized 15kW rooftop solar microgrid.',
    matchScoreForTarget: 92,
  },
];

export const INITIAL_PLACEMENTS: PlacementOutcome[] = [
  {
    id: 'place-1',
    studentName: 'Siddhesh Kulkarni',
    instituteName: 'Government Polytechnic Pune',
    district: 'Pune',
    companyName: 'Tata Motors EV Division',
    role: 'EV Assembly Quality Associate',
    salaryINR: 680000,
    placementDate: '2026-08-15',
    sector: 'Automotive & EV',
    skillUtilizationRate: 94,
    retentionMonths: 14,
  },
  {
    id: 'place-2',
    studentName: 'Ananya Joshi',
    instituteName: 'VJTI Mumbai',
    district: 'Mumbai',
    companyName: 'L&T Infotech (LTIMindtree)',
    role: 'Cloud Operations Trainee',
    salaryINR: 840000,
    placementDate: '2026-07-20',
    sector: 'Information Technology',
    skillUtilizationRate: 91,
    retentionMonths: 12,
  },
  {
    id: 'place-3',
    studentName: 'Kunal Jadhav',
    instituteName: 'ITI Nashik',
    district: 'Nashik',
    companyName: 'Bosch Chassis Systems India',
    role: 'CNC Precision Operator',
    salaryINR: 460000,
    placementDate: '2026-06-10',
    sector: 'Advanced Manufacturing',
    skillUtilizationRate: 78,
    retentionMonths: 16,
  },
  {
    id: 'place-4',
    studentName: 'Pooja Chavan',
    instituteName: 'Government ITI Aurangabad',
    district: 'Aurangabad',
    companyName: 'Adani Green Energy Ltd.',
    role: 'Solar Commissioning Technician',
    salaryINR: 530000,
    placementDate: '2026-08-01',
    sector: 'Renewable Energy',
    skillUtilizationRate: 88,
    retentionMonths: 10,
  },
  {
    id: 'place-5',
    studentName: 'Gaurav Sawant',
    instituteName: 'Government Polytechnic Kolhapur',
    district: 'Kolhapur',
    companyName: 'Kirloskar Oil Engines',
    role: 'Industrial Mechatronics Specialist',
    salaryINR: 520000,
    placementDate: '2026-05-18',
    sector: 'Advanced Manufacturing',
    skillUtilizationRate: 82,
    retentionMonths: 18,
  },
];

export const DISTRICTS_MAHARASHTRA = [
  'Pune',
  'Mumbai',
  'Nagpur',
  'Nashik',
  'Aurangabad (Chhatrapati Sambhajinagar)',
  'Thane',
  'Kolhapur',
  'Solapur',
  'Amravati',
  'Nanded',
];
